name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |-
          sudo apt-get update
          sudo apt-get --yes install calibre

      - name: setup git config
        run: |-
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Build ebook
        run: |-
          ./scripts/build.sh

      - name: Commit dist files
        run: |-
          git status -sb
          git add ma-petite-yvette.epub
          git commit -m'chore: update epub'
          git push origin HEAD


